services:
  elasticsearch:
    image: elasticsearch:8.15.2
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - "xpack.security.enabled=false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch
      - ./shared/elasticsearch/:/shared/
    networks:
      - elk

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: flask-frontend
    ports:
      - "5050:5050"
    volumes:
      - ./logfiles:/app/logfiles
    networks:
      - elk
    depends_on:
      - elasticsearch
      - redis
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  logstash:
    image: logstash:8.15.2
    container_name: logstash
    ports:
      - 5000:5000
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logfiles:/usr/share/logstash/logs
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:8.15.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - elk
    depends_on:
      - elasticsearch

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - elk

networks:
  elk:
    driver: bridge

volumes:
  esdata:
    driver: local
  logstash:
    driver: local
