services:
  elasticsearch:
    image: elasticsearch:8.15.2
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - "xpack.security.enabled=false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch
      - ./shared/elasticsearch/:/shared/
    networks:
      - elk
  logstash:
    image: logstash:8.15.2
    container_name: logstash
    ports:
      - 5000:5000
    volumes:
      #- ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logfiles/:/usr/share/logstash/logs/
      # - ./logfiles/auth.log:/usr/share/logstash/logs/auth.log
      # - ./logfiles/syslog.log:/usr/share/logstash/logs/syslog
      # - ./logfiles/kern.log:/usr/share/logstash/logs/kern.log
      # - ./logfiles/history.log:/usr/share/logstash/logs/history.log
      # - ./logfiles/sysd.json:/usr/share/logstash/logs/sysd.json
    networks:
      - elk
    depends_on:
      - elasticsearch
  kibana:
    image: kibana:8.15.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - elk
    depends_on:
      - elasticsearch

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - elk

networks:
  elk:
    driver: bridge

volumes:
  esdata:
    driver: local
  logstash:
    driver: local
